baseURL = 'http://mbosley.github.io/'
languageCode = 'en-us'
title = 'Mitchell Bosley'
theme = 'cactus'
copyright = "Mitchell Bosley" # cactus will use title if copyright is not set

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Dissertation"
url = "/dissertation"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Teaching"
url = "/teaching"
weight = 4

# [[menu.main]]
# name = "Posts"
# url = "/posts"
# weight = 4

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 5


[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  cvLink = "/cv/cv-bosley.pdf"
  colortheme = "classic" # dark, light, white, or classic
  rss = false # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  description = "I am a PhD candidate in the Department of Political Science at the University of Michigan studying legislative institutions and political methodology. My research focuses on the relationship between unwritten norms and formal rules in legislatures, and the process by which rule changes either codify or undermine these norms.\n\n I am also interested in the development and applications of statistical methods for political science research, particularly those related to Large Language Models (LLMs) such as BERT and GPT.\n\n [See my CV here.](/cv/cv-bosley.pdf)"
  mainSection = "blog" # your main section
  mainSectionTitle = " "
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 1 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  # showProjectsList = true # show projects list by default (if projects data file exists).
  # projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default
  favicon = false


  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = false # default
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  [[params.social]]
    name = "email"
    link = "mcbosley@umich.edu"  # no need for "mailto:" in the head
  [[params.social]]
    name = "github"
    link = "https://github.com/mbosley"
  [[params.social]]
    name = "twitter"
    link = "https://www.twitter.com/mitchellbosley"
